
def complement(dna_str):
    dna_str = dna_str
    complement_str= ""

    for i in range(len(dna_str)):
        if dna_str[i] == 'A':
            complement_str += 'T'
        elif dna_str[i] == 'T':
            complement_str += 'A'
        elif dna_str[i] == 'G':
            complement_str += 'C'
        elif dna_str[i] == 'C':
            complement_str += 'G'
        else:
            return 'Error'

    return complement_str[::-1]

print(complement('ACGTGCGATACTCGTCGCAATTGCCTTTCTGCCGTTTTCCTGCTCTTGTACCCTTTTTCCGACAGTAACGCGTTCGTCTGGGCCAAAGCGGGTGTCCATGCTTAATAACAGGCCATCATAGGGATGCGACAGAGTTACGGGTCCGCTCTGTCCCTACGTGACACTCCAGCTGATAAGAATATGGTAAGTCCTGTTTCGGAACAGAATTACGTACACGGTGTCGGCATTTAGATATTCTCGAGCGGAGTTGCACCCCATGTGAGCGTTTCGCCCTTTCTGAGGGTGCCAGCTTTGCTCCCGTTCGACCCCCAGAAGAATAGCTCCAGGACGGAATCCGAAGGTCTTGAATTATGGCTTTGCGCCTCACCGCTGTATTCTCTTCCAAGGACGGCGTCACAAGCAACTATGGAACAGATGCTTTAGGTGAATAAGACCGCTTCAATGGTACGGCGACAAATCGTTGGCACGGAGCCCGTCATAATGCCATACCGTCTTATAGCTTAGTGGGGGGTTAATTATCAACTGTAGTCAATAGGTCGCAGACGATGTCCCATGTAGCTCGGTAATTTTACTAATATATAGCGCAGAGCGTCACGCAAAAACGCGGTAGTCCATGTAATTCCCACGCAACATCTCACGGCATGATATTCGACGAAGCACCCTTCAAATCATGGGATCTTGAATCGACAGGGGTTTCGAAACTTGATGCTAAGACATCGAATATTAAGATACCAATATTCGGTCTCCGAGTGAGATGATATGCCAAAAATTACGCAGCGAGGTGGTCAATCAGGGTGGAGTGTGGGTGAGGTTCCCTACGAGGCGAGTTCAGTGGATCAGCCGGATTCACTATAGTGCAACATATTTACGTCCCTTCATGGTCACCCGGGAACGTTCCTATGTTTATAGCAACGCGCGACGGACCTCAACGGCGGG'))