
def find_motif(str1, str2):
    str1 = str1.upper()
    str2 = str2.upper()
    str2_len = len(str2)
    positions = ''

    for i in range(len(str1)):
        if str1[i: i + str2_len] == str2:
            positions += str(i + 1) + " "
        else:
            positions += ''

    return(positions)


print(find_motif("GTCACCTTATCAGTCACCTTTTCACCTTTTCATCACCTTGCCTCACCTTTCACCTTTCACCTTTCACCTTCGTATCACCTTCCCCTCACCTTTAGGGGCTACACTCACCTTTCACCTTTTGCTATCACCTTCTCACCTTATCTCTTCACCTTTCACCTTTCAAAGCTCACCTTTCATCACCTTTCACCTTATCACCTTTCACCTTCTCACCTTTCACCTTAATCACCTTTCACCTTCCTCACCTTCATCTACCATCACCTTTCACCTTTCACCTTGCAGTGGTCACCTTTTCACCTTTCAGGTCACCTTTTCACCTTGAAGTAATCACCTTATATATTCACCTTATCACCTTTCACCTTGTAGTCACCTTGTGCTCACCTTTCACCTTTTTCACCTTATCCCGATCACCTTCCTAGATACATACACGGTCACCTTTCACCTTGTCGTGTTTCTCACTTCACCTTTCACCTTCTCCCTCACCTTCTCACCTTGGTCACCTTTCACCTTATCACCTTCTCACCTTTTATGTTCACCTTTCACCTTATTGCATCGGTCACCTTTCACCTTTCACCTTGAATCCCTCACCTTTCACCTTTCAGTCACCTTACTCACCTTTCACCTTCTCACCTTAGCAGTTCACCTTTTTCACCTTTCGTTCACCTTTCACCTTTCACCTTTCACCTTTGGGTTATCACCTTATCACCTTTCACCTTTGTGGTTCACCTTTCACCTTGGGCTCACCTTGACGCTCACCTTGTCACCTTTTATCCACTTCACCTTTATCACCTTTATCACCTTTCACCTT", "TCACCTTTC"))
