
def transcribe(dna_string):
    dna_string = dna_string.upper()
    rna_string = ''

    for i in range(len(dna_string)):
        if dna_string[i] == 'T':
            rna_string += 'U'
        else:
            rna_string += dna_string[i]

    return rna_string

print(transcribe('ATGTGCTCATGAGTTAACGTAGGCAGGTAAGCGTGTTCTGGACCAGATATGGTTATGATCACCTCCCGGTGTCCGTTTTAGTACAAGGCGTCTCAATGAACTTTGCTATCATTGTGTGGGCGCTTCTAGTAAGTACTATTCCACTTTCGCATCCGATATCGCTGTGCCATAATTAAGTATAGAAACATCACTTTGTGGTAGATCCTATAAAGACGTCAGGTTATCATGGGAAAAGGCTATGCGCTGAAGAGGGTATCGTCGACCGACAGTTGGAATTATCGTTACGTCTCGCAGCGCGGGCATCACCCCCTATTCCTCCTCTGAAAAGTGTGGTTTTGATTGCTGACAAGCGAGTAAAGTAATGGGTCGCCGCAAGACGGCACTGGTAAATCTCAATGGTATGTGATCCTCGATCTACGCCCTCCGCTTCTGCGTGTGACTGCAATGATTCGGTCCCGCACTAAGGGAGAAATATTGTGGCTCCCTGCTCTGCTCCTATTGCTTATGCTCGTCTTCGGTGTCAAGAAAGGGTCCCATAAAAGAGATACCCCTTAGCAGTACTCTGGAGTCTCTGCTAGAGGGCTAAGTTTTTGACCTGTGCGTCCCGCCGATTTACCGAATTGAGGGGTCCTGGCAGTTAGCAGGCCCCTCGCGACATCTAACCCAGCCAGCATGACACCTGTCCTGCAGAGTTGCAAGACACGTATGAGCACGTCGCGGGTCTAAATCTCTGGGGCTTTAATCATGCTCACCCACATGTATTGTGTGGTAGCTTGTGTCGTGGTCCGTGAAATCGCCACTTTCTTTAGCGCATCTGTTTCGCAATGCCCGTCAACGGTTGGGGTATGGACTGTCATTGGGACGTCGGAACAGGAAACCACAATCTCGCCGCTGGACGGTCACGATATAGCTCGGCGCCAGGAA'))